### ISSUE TITLE
iOS 16.5

### ISSUE THREAD

**Issue by maz0uzi** [0xallie/apfs-reseal#1]
Hello, 
Thanks for making this tool, is it okay to use it with iOS 16.5?

**Comment by ghost** [comment]
Not yet, I need to update the ramdisk script.

If you can't wait, just update to iOS 16.5.1 (not restore, so you don't lose your data) instead of using this script, that will also fix your recovery loop.

**Comment by maz0uzi** [comment]
Alright, thank you so much ✨
